export const CREATE_FREQUENCY_REQUEST = "CREATE_FREQUENCY_REQUEST";
export const CREATE_FREQUENCY_SUCCESS = "CREATE_FREQUENCY_SUCCESS";
export const CREATE_FREQUENCY_FAIL = "CREATE_FREQUENCY_FAIL";

export const LIST_FREQUENCY_REQUEST = "LIST_FREQUENCY_REQUEST";
export const LIST_FREQUENCY_SUCCESS = "LIST_FREQUENCY_SUCCESS";
export const LIST_FREQUENCY_FAIL = "LIST_FREQUENCY_FAIL";
