// role contants
export const CREATE_ROLE_REQUEST = "CREATE_ROLE_REQUEST";
export const CREATE_ROLE_SUCCESS = "CREATE_ROLE_SUCCESS";
export const CREATE_ROLE_FAIL = "CREATE_ROLE_FAIL";
export const CREATE_ROLE_RESET = "CREATE_ROLE_RESET";

export const LIST_ROLE_REQUEST = "LIST_ROLE_REQUEST";
export const LIST_ROLE_SUCCESS = "LIST_ROLE_SUCCESS";
export const LIST_ROLE_FAIL = "LIST_ROLE_FAIL";
